name: Reviewdog
on: [pull_request]
permissions:
  pull-requests: write

jobs:
  python_check:
    strategy:
      matrix:
        workdir:
          - .
    name: python_check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Setup Reviewdog with action
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # - name: Setup reviewdog on Github Action
      #   run: |
      #     mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
      #     echo ::add-path::$HOME/bin

      - name: Install Libraries
        run: |
          pip install black==23.1.0 bandit==1.7.5 poetry==1.4.0 poetry-audit-plugin==0.3.0
          
      - name: Poetry Install
        run: |    
          poetry self add poetry-audit-plugin
          poetry install
      
      # - name: Security Check by bandit
      #   run: |
      #     bandit -r . | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review

      - name: Check Packages
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
        run: poetry run pip-audit | reviewdog -reporter=github-pr-review

      # - name: black
      #   uses: reviewdog/action-black@v3
      #   with:
      #     black_args: "--config ./pyproject.toml"
      #     github_token: ${{ secrets.github_token }}
      #     reporter: github-pr-review
      #     fail_on_error: true
      #     filter_mode: nofilter
      #     workdir: ${{ matrix.workdir }}

